title: MyCompany Security Content
email: research@myco.com
description: >- # this means to ignore newlines until "baseurl:"
  This project gives you access to your repository of Analytic Stories,
  security guides that provide background on tactics, techniques and procedures (TTPs),
  mapped to the MITRE ATT&CK Framework, the Lockheed Martin Cyber Kill Chain, and CIS Controls.
  They include Splunk searches, machine learning algorithms and
  Splunk Phantom playbooks (where available)—all designed to work together to detect, investigate, and respond to threats.
name: MyCo Threat Research Team (STRT)
url: "https://dlamspl.github.io"
baseurl: "/security_content_package/" # the subpath of your site, e.g. /blog
url: "https://dlamspl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: dlamspl/security_content_package
logo: "/static/logo.png"
#teaser: "/static/logo.png"
masthead_title: "Security Content"
words_per_minute: 200
search: true
search_full_content: true
# Social Sharing
twitter:
  username: splunk
twitter_username: splunk
github_username: splunk

# Build settings
#theme: minimal-mistakes-jekyll
#remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast" #default, neon, dark are also options
#minimal_mistakes_skin: "neon"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : "Splunk Threat Reasearch Team (STRT)"
  avatar           : "/static/team_photo.png"
  bio              : "We help security teams around the globe strengthen operations by providing tactical guidance and insights to detect, investigate and respond against the latest threats."
  location         : "The Mothership"
  email            : "research@splunk.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.splunk.com/en_us/cyber-security/threat-research.html"
      #
# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/splunk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/splunk/security_content"

collections:
  stories:
    output: true
    permalink: /:collection/:path/
  playbooks:
    output: true
    permalink: /:collection/:path/

defaults:
  # _docs
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
      toc: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _analytic_stories
  - scope:
      path: "_stories"
      type: stories
    values:
      layout: single
      author_profile: false
      comments: false
      share: true
      related: false
      toc: true
  # _playbooks
  - scope:
      path: "_playbooks"
      type: playbooks
    values:
      layout: single
      author_profile: false
      comments: false
      share: true
      related: true
      toc: true
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-294P2LYRR5"
    anonymize_ip: false # default
